spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: t60564533@gmail.com
    password: 1234qwer!q
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:mypassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev  # ???? ??????????? ?????? ?????????
    drop-first: false
    default-schema: public
  profiles:
    active: dev
jwt:
  secret: mysupersecretkeythatshouldbeatleast32byteslong!
settings:
  application_url: localhost:8080