version: '3.8'

services:
  db:
    image: postgres:15
    container_name: appl-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: auth-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - db