version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false # если используешь шаблоны
server:
  port: 8080